package com.sreenu.Spring_boot_demo.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sreenu.Spring_boot_demo.model.Employee;
import com.sreenu.Spring_boot_demo.service.EmployeeService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.NoSuchElementException;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(EmployeeV2Controller.class)
@DisplayName("Employee V2 Controller Integration Tests")
class EmployeeV2ControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean(name = "employeeV2ServiceImpl")
    private EmployeeService employeeService;

    @Autowired
    private ObjectMapper objectMapper;

    private Employee testEmployee;

    @BeforeEach
    void setUp() {
        testEmployee = createTestEmployee();
    }

    private Employee createTestEmployee() {
        Employee employee = new Employee();
        employee.setEmployeeId("EMP001");
        employee.setFirstName("John");
        employee.setLastName("Doe");
        employee.setEmailId("john.doe@example.com");
        employee.setDepartmentId("DEPT001");
        return employee;
    }

    @Test
    @DisplayName("POST /v2/employees - Should create employee successfully")
    void testCreateEmployeeSuccess() throws Exception {
        // Given
        when(employeeService.save(any(Employee.class))).thenReturn(testEmployee);

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.employeeId").value("EMP001"))
                .andExpect(jsonPath("$.firstName").value("John"))
                .andExpect(jsonPath("$.lastName").value("Doe"))
                .andExpect(jsonPath("$.emailId").value("john.doe@example.com"))
                .andExpect(jsonPath("$.departmentId").value("DEPT001"));

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("POST /v2/employees - Should create employee with auto-generated ID")
    void testCreateEmployeeWithAutoGeneratedId() throws Exception {
        // Given
        Employee employeeWithoutId = new Employee();
        employeeWithoutId.setFirstName("Jane");
        employeeWithoutId.setLastName("Smith");
        employeeWithoutId.setEmailId("jane.smith@example.com");

        Employee savedEmployee = new Employee();
        savedEmployee.setEmployeeId("auto-generated-uuid");
        savedEmployee.setFirstName("Jane");
        savedEmployee.setLastName("Smith");
        savedEmployee.setEmailId("jane.smith@example.com");

        when(employeeService.save(any(Employee.class))).thenReturn(savedEmployee);

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(employeeWithoutId)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.employeeId").value("auto-generated-uuid"))
                .andExpect(jsonPath("$.firstName").value("Jane"))
                .andExpect(jsonPath("$.lastName").value("Smith"))
                .andExpect(jsonPath("$.emailId").value("jane.smith@example.com"));

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("POST /v2/employees - Should handle invalid JSON")
    void testCreateEmployeeWithInvalidJson() throws Exception {
        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{ invalid json }"))
                .andExpect(status().isBadRequest());

        verify(employeeService, never()).save(any(Employee.class));
    }

    @Test
    @DisplayName("POST /v2/employees - Should handle service layer exceptions")
    void testCreateEmployeeWithServiceException() throws Exception {
        // Given
        when(employeeService.save(any(Employee.class)))
                .thenThrow(new RuntimeException("Database connection failed"));

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isInternalServerError());

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("GET /v2/employees - Should return all employees")
    void testGetAllEmployeesSuccess() throws Exception {
        // Given
        Employee employee2 = createTestEmployee();
        employee2.setEmployeeId("EMP002");
        employee2.setFirstName("Jane");
        employee2.setEmailId("jane.doe@example.com");

        List<Employee> employees = Arrays.asList(testEmployee, employee2);
        when(employeeService.getAllEmployees()).thenReturn(employees);

        // When & Then
        mockMvc.perform(get("/v2/employees"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].employeeId").value("EMP001"))
                .andExpect(jsonPath("$[0].firstName").value("John"))
                .andExpect(jsonPath("$[1].employeeId").value("EMP002"))
                .andExpect(jsonPath("$[1].firstName").value("Jane"));

        verify(employeeService, times(1)).getAllEmployees();
    }

    @Test
    @DisplayName("GET /v2/employees - Should return empty list when no employees")
    void testGetAllEmployeesEmpty() throws Exception {
        // Given
        when(employeeService.getAllEmployees()).thenReturn(Collections.emptyList());

        // When & Then
        mockMvc.perform(get("/v2/employees"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.length()").value(0));

        verify(employeeService, times(1)).getAllEmployees();
    }

    @Test
    @DisplayName("GET /v2/employees - Should handle service exceptions")
    void testGetAllEmployeesWithServiceException() throws Exception {
        // Given
        when(employeeService.getAllEmployees())
                .thenThrow(new RuntimeException("Database query failed"));

        // When & Then
        mockMvc.perform(get("/v2/employees"))
                .andExpect(status().isInternalServerError());

        verify(employeeService, times(1)).getAllEmployees();
    }

    @Test
    @DisplayName("GET /v2/employees/{id} - Should return employee by ID")
    void testGetEmployeeByIdSuccess() throws Exception {
        // Given
        when(employeeService.getAllEmployeesById("EMP001")).thenReturn(testEmployee);

        // When & Then
        mockMvc.perform(get("/v2/employees/EMP001"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.employeeId").value("EMP001"))
                .andExpect(jsonPath("$.firstName").value("John"))
                .andExpect(jsonPath("$.lastName").value("Doe"))
                .andExpect(jsonPath("$.emailId").value("john.doe@example.com"))
                .andExpect(jsonPath("$.departmentId").value("DEPT001"));

        verify(employeeService, times(1)).getAllEmployeesById("EMP001");
    }

    @Test
    @DisplayName("GET /v2/employees/{id} - Should handle employee not found")
    void testGetEmployeeByIdNotFound() throws Exception {
        // Given
        when(employeeService.getAllEmployeesById("NONEXISTENT"))
                .thenThrow(new NoSuchElementException("Employee not found"));

        // When & Then
        mockMvc.perform(get("/v2/employees/NONEXISTENT"))
                .andExpect(status().isInternalServerError());

        verify(employeeService, times(1)).getAllEmployeesById("NONEXISTENT");
    }

    @Test
    @DisplayName("GET /v2/employees/{id} - Should handle UUID format IDs")
    void testGetEmployeeByIdWithUUID() throws Exception {
        // Given
        String uuidId = "550e8400-e29b-41d4-a716-446655440000";
        testEmployee.setEmployeeId(uuidId);
        when(employeeService.getAllEmployeesById(uuidId)).thenReturn(testEmployee);

        // When & Then
        mockMvc.perform(get("/v2/employees/" + uuidId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.employeeId").value(uuidId))
                .andExpect(jsonPath("$.firstName").value("John"));

        verify(employeeService, times(1)).getAllEmployeesById(uuidId);
    }

    @Test
    @DisplayName("DELETE /v2/employees/{id} - Should delete employee successfully")
    void testDeleteEmployeeByIdSuccess() throws Exception {
        // Given
        String expectedMessage = "Employee deleted with id: EMP001";
        when(employeeService.deleteEmployeeById("EMP001")).thenReturn(expectedMessage);

        // When & Then
        mockMvc.perform(delete("/v2/employees/EMP001"))
                .andExpect(status().isOk())
                .andExpect(content().string(expectedMessage));

        verify(employeeService, times(1)).deleteEmployeeById("EMP001");
    }

    @Test
    @DisplayName("DELETE /v2/employees/{id} - Should handle delete when employee not found")
    void testDeleteEmployeeByIdNotFound() throws Exception {
        // Given - V2 service doesn't throw exception for non-existent deletes, it just deletes silently
        String expectedMessage = "Employee deleted with id: NONEXISTENT";
        when(employeeService.deleteEmployeeById("NONEXISTENT")).thenReturn(expectedMessage);

        // When & Then
        mockMvc.perform(delete("/v2/employees/NONEXISTENT"))
                .andExpect(status().isOk())
                .andExpect(content().string(expectedMessage));

        verify(employeeService, times(1)).deleteEmployeeById("NONEXISTENT");
    }

    @Test
    @DisplayName("DELETE /v2/employees/{id} - Should handle service exceptions")
    void testDeleteEmployeeByIdWithServiceException() throws Exception {
        // Given
        when(employeeService.deleteEmployeeById("EMP001"))
                .thenThrow(new RuntimeException("Database delete failed"));

        // When & Then
        mockMvc.perform(delete("/v2/employees/EMP001"))
                .andExpect(status().isInternalServerError());

        verify(employeeService, times(1)).deleteEmployeeById("EMP001");
    }

    @Test
    @DisplayName("Should validate content type for POST requests")
    void testPostWithoutContentType() throws Exception {
        // When & Then
        mockMvc.perform(post("/v2/employees")
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isUnsupportedMediaType());

        verify(employeeService, never()).save(any(Employee.class));
    }

    @Test
    @DisplayName("Should handle empty request body for POST")
    void testPostWithEmptyBody() throws Exception {
        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(""))
                .andExpect(status().isBadRequest());

        verify(employeeService, never()).save(any(Employee.class));
    }

    @Test
    @DisplayName("Should handle null employee fields correctly")
    void testCreateEmployeeWithNullFields() throws Exception {
        // Given
        Employee employeeWithNulls = new Employee();
        employeeWithNulls.setFirstName("John");
        // Other fields are null

        Employee savedEmployee = new Employee();
        savedEmployee.setEmployeeId("EMP003");
        savedEmployee.setFirstName("John");

        when(employeeService.save(any(Employee.class))).thenReturn(savedEmployee);

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(employeeWithNulls)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.employeeId").value("EMP003"))
                .andExpect(jsonPath("$.firstName").value("John"));

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("Should handle large employee data")
    void testCreateEmployeeWithLargeData() throws Exception {
        // Given
        Employee largeEmployee = new Employee();
        largeEmployee.setEmployeeId("EMP-LARGE-001");
        largeEmployee.setFirstName("A".repeat(100));
        largeEmployee.setLastName("B".repeat(100));
        largeEmployee.setEmailId("test@example.com");
        largeEmployee.setDepartmentId("DEPT-LARGE-001");

        when(employeeService.save(any(Employee.class))).thenReturn(largeEmployee);

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(largeEmployee)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.employeeId").value("EMP-LARGE-001"))
                .andExpect(jsonPath("$.firstName").value("A".repeat(100)));

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("Should handle special characters in employee data")
    void testCreateEmployeeWithSpecialCharacters() throws Exception {
        // Given
        Employee specialEmployee = new Employee();
        specialEmployee.setEmployeeId("EMP-SPECIAL_001");
        specialEmployee.setFirstName("José-María");
        specialEmployee.setLastName("O'Connor");
        specialEmployee.setEmailId("jose.maria+test@example.com");
        specialEmployee.setDepartmentId("DEPT-001_SPECIAL");

        when(employeeService.save(any(Employee.class))).thenReturn(specialEmployee);

        // When & Then
        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(specialEmployee)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.employeeId").value("EMP-SPECIAL_001"))
                .andExpect(jsonPath("$.firstName").value("José-María"))
                .andExpect(jsonPath("$.lastName").value("O'Connor"))
                .andExpect(jsonPath("$.emailId").value("jose.maria+test@example.com"));

        verify(employeeService, times(1)).save(any(Employee.class));
    }

    @Test
    @DisplayName("Should handle concurrent requests properly")
    void testConcurrentRequests() throws Exception {
        // Given
        when(employeeService.getAllEmployees()).thenReturn(Arrays.asList(testEmployee));
        when(employeeService.getAllEmployeesById(anyString())).thenReturn(testEmployee);
        when(employeeService.save(any(Employee.class))).thenReturn(testEmployee);
        when(employeeService.deleteEmployeeById(anyString())).thenReturn("Employee deleted with id: EMP001");

        // When & Then - Simulate concurrent requests
        mockMvc.perform(get("/v2/employees"))
                .andExpect(status().isOk());

        mockMvc.perform(get("/v2/employees/EMP001"))
                .andExpect(status().isOk());

        mockMvc.perform(post("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isOk());

        mockMvc.perform(delete("/v2/employees/EMP001"))
                .andExpect(status().isOk());

        // Verify all requests were processed
        verify(employeeService, times(1)).getAllEmployees();
        verify(employeeService, times(1)).getAllEmployeesById("EMP001");
        verify(employeeService, times(1)).save(any(Employee.class));
        verify(employeeService, times(1)).deleteEmployeeById("EMP001");
    }

    @Test
    @DisplayName("Should handle HTTP methods correctly")
    void testHttpMethodsValidation() throws Exception {
        // Test that wrong HTTP methods return appropriate errors
        
        // PUT method not supported on base endpoint
        mockMvc.perform(put("/v2/employees")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isMethodNotAllowed());

        // PATCH method not supported
        mockMvc.perform(patch("/v2/employees/EMP001")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(testEmployee)))
                .andExpect(status().isMethodNotAllowed());

        // Verify no service methods were called for unsupported methods
        verify(employeeService, never()).save(any(Employee.class));
        verify(employeeService, never()).getAllEmployeesById(anyString());
    }

    @Test
    @DisplayName("Should handle malformed URLs gracefully")
    void testMalformedUrls() throws Exception {
        // Test endpoint with extra path segments
        mockMvc.perform(get("/v2/employees/EMP001/extra"))
                .andExpect(status().isNotFound());

        // Test endpoint with invalid characters that might cause issues
        mockMvc.perform(get("/v2/employees/EMP001/"))
                .andExpect(status().isNotFound());

        verify(employeeService, never()).getAllEmployeesById(anyString());
    }
}